apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helloworld.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "helloworld.fullname" .}}